{ ... }:
{
  flake.modules.nixos.princedimond-gui =
    { pkgs, ... }:
    {
      nixpkgs.config.allowUnfreePackages = [
        "discord"
        #"yed"
        "anytype"
        "anytype-heart"
        "zoom"
        "hubstaff"
        "microsoft-edge"
        "expressvpn"
        "winbox"
        "lunacy"
        "davinci-resolve"
      ];
      environment.systemPackages = with pkgs; [
        ferdium
        discord
        #element-desktop
        thunderbird
        onlyoffice-desktopeditors
        #kdePackages.calligra
        libreoffice-qt-fresh
        stirling-pdf-desktop
        freeplane
        #nputs.nixpkgs-unstable.dia
        #yed
        affine
        anytype
        siyuan
        #logseq
        joplin-desktop
        kdePackages.marknote
        notesnook
        kdePackages.konversation
        quasselClient
        zoom
        hubstaff
        proton-vpn
        microsoft-edge
        expressvpn
        tailscale
        remmina
        wireguard-ui
        wireguard-tools
        deluge
        winbox4
        waynergy
        gthumb
        imagemagick
        graphicsmagick-imagemagick-compat
        orca-slicer
        openscad
        #freecad
        #freecad-wayland
        lunacy
        obs-studio
        #kdePackages.kdenlive
        krita
        davinci-resolve
        handbrake
        devede
        cheese
        kooha
        bitwarden-desktop
        thunar
        gnome-disk-utility
        system-config-printer
        naps2
        flatpak
        teamviewer
        warp-terminal
        zed-editor
        #virt-manager
        virt-viewer
        spice-gtk
        spice-protocol
        #hollywood
        ventoy-full
        ventoy-full-qt
        virtio-win
        win-spice
        czkawka-full
        wl-clipboard
        rpi-imager
        appimage-run
        xivlauncher
        steam
        heroic
        umu-launcher
        protonup-ng
        protonup-qt
        hplipWithPlugin
        hplip
        wine
        wine64
        wine-wayland
        thunderbolt
        solaar
      ];
    };
}
